# Generated by Django 3.2.12 on 2022-03-03 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meta_and_inheritance', '0002_auto_20220303_0924'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderedworker',
            options={'ordering': ['first_name', 'startwork_date']},
        ),
    ]
